# Generated by Django 2.2 on 2021-06-23 05:47

import apps.taplink.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TapLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pathname', models.SlugField(blank=True, null=True, unique=True, verbose_name='Pathname')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=apps.taplink.utils.image_upload_to, verbose_name='Avatar')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='taplink', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Messenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram')),
                ('title_t', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram title')),
                ('whatsapp', models.CharField(blank=True, max_length=50, null=True, verbose_name='WhatsApp')),
                ('title_wa', models.CharField(blank=True, max_length=50, null=True, verbose_name='WhatsApp title')),
                ('taplink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messengers', to='taplink.TapLink', verbose_name='TapLink')),
            ],
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editor', models.TextField(verbose_name='Editor')),
                ('taplink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editors', to='taplink.TapLink', verbose_name='TapLink')),
            ],
        ),
    ]
