# Generated by Django 2.2 on 2021-08-13 10:17

import apps.taplink.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taplink', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editor',
            options={'verbose_name': 'Редактор', 'verbose_name_plural': 'Редакторы'},
        ),
        migrations.AlterModelOptions(
            name='messenger',
            options={'verbose_name': 'Мессенджер', 'verbose_name_plural': 'Мессенджеры'},
        ),
        migrations.AlterModelOptions(
            name='taplink',
            options={'verbose_name': 'Таплинк', 'verbose_name_plural': 'Таплинк'},
        ),
        migrations.AlterField(
            model_name='editor',
            name='taplink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editors', to='taplink.TapLink', verbose_name='Таплинк'),
        ),
        migrations.AlterField(
            model_name='messenger',
            name='title_t',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Название Telegram'),
        ),
        migrations.AlterField(
            model_name='messenger',
            name='title_wa',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Название WhatsApp'),
        ),
        migrations.AlterField(
            model_name='taplink',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=apps.taplink.utils.image_upload_to, verbose_name='Аватарка'),
        ),
        migrations.AlterField(
            model_name='taplink',
            name='pathname',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Путь'),
        ),
        migrations.AlterField(
            model_name='taplink',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='taplink', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
