# Generated by Django 2.2 on 2021-05-06 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taplink', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taplink',
            name='url',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='taplinkeditor',
            name='taplink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editors', to='taplink.TapLink', verbose_name='TapLink'),
        ),
        migrations.AlterField(
            model_name='taplinkmessenger',
            name='taplink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messengers', to='taplink.TapLink', verbose_name='TapLink'),
        ),
    ]
