# Generated by Django 2.2 on 2021-06-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taplink', '0002_auto_20210518_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taplink',
            name='nickname',
        ),
        migrations.AddField(
            model_name='taplink',
            name='pathname',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Pathname'),
        ),
    ]
