# Generated by Django 2.2 on 2021-05-31 10:32

import apps.shop.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_name', models.CharField(max_length=200, unique=True, verbose_name='Collection')),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ('collection_name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250, verbose_name='Product')),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='New price')),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Old price')),
                ('is_available', models.BooleanField(default=True, verbose_name='Available')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.Collection', verbose_name='Collections')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='Seller')),
            ],
            options={
                'ordering': ('product_name',),
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=apps.shop.utils.image_upload_to, verbose_name='Image')),
                ('is_default', models.BooleanField()),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.Product', verbose_name='Products')),
            ],
        ),
    ]
