# Generated by Django 2.2 on 2021-06-03 07:34

import apps.shop.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='is_default',
        ),
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, upload_to=apps.shop.utils.image_upload_to, verbose_name='Main image'),
        ),
    ]
