# Generated by Django 2.2 on 2021-07-26 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('НАЛИЧНЫМИ', 'Наличными'), ('ОНЛАЙН ОПЛАТА', 'Онлайн оплата')], default='НАЛИЧНЫМИ', max_length=100, verbose_name='Payment method'),
        ),
    ]
